file1 = open("txtfile.txt","w")
l = ["this is delhi\n","this is paris\n","this is chennai \n"]
file1.write("hello \n")
file1.writelines(l)
file1.close()
file1=open("txtfile.txt","r+")
print("Output of read function is \n")
print(file1.read())
print()
file1.seek(0)
print("output of readline(2) function is : ")
print(file1.readline(2))   
print()
file1.seek(0)
print("output of Read(9) function is  : ")
print(file1.read(9))
print()
file1.seek(0)
print("output of readline(9) function is : ")
print(file1.readline(9))
print()
file1.seek(0)
print("output of readlines function is : ")
print(file1.readlines())